### PR TITLE
Major project structure cleanup, organize colors, get rid of XIB cells

### PR DESCRIPTION
**Pull request by kenan-mamedoff**

### CODE REVIEW

**Comment by gvh** [comment]
There are quite a number of issues called out in the sonar cloud report, I especially noted the shadowed variable names like interactor.  The stuff about comments, parameter count, complexity, todos, etc can be ignored for the moment, but some of the stuff about shadowing class variables looks like it should be addressed.

**Comment by kenan-mamedoff** [comment]
> There are quite a number of issues called out in the sonar cloud report, I especially noted the shadowed variable names like interactor. The stuff about comments, parameter count, complexity, todos, etc can be ignored for the moment, but some of the stuff about shadowing class variables looks like it should be addressed.

I don't think I can do much about variables in Clean Cycle. They have to be there to complete the cycle. It is in every screen/cycle created by Equaleyes. Part of the template.

image

**Review by gvh — APPROVED** [review]
Approved, but would later like to understand why a template includes this construct; i don't like a template causing code review issues.

**Comment by kenan-mamedoff** [comment]
> Approved, but would later like to understand why a template includes this construct; i don't like a template causing code review issues.

Totally understandable. This is our old template that we have been using 5ish years in the company. The new template with all the dependencies/goodies that gets rid of most of the code duplication and handles it in base class, is iOS 13+ (Fabriik is iOS 12) and since we didn't have much time to do architecture planning or to update dependencies, I used the old template.

**Pull request merged**
